Repository anz-bank/go-course, pull requests merged in 2019-09, with the labels that each got.

#619 Lab8
  08_project/nickolee/README.md
  08_project/nickolee/cmd/puppy-server/main.go
  08_project/nickolee/cmd/puppy-server/main_test.go
  08_project/nickolee/pkg/puppy/error_test.go
  08_project/nickolee/pkg/puppy/errors.go
  08_project/nickolee/pkg/puppy/store/mapstore.go
  08_project/nickolee/pkg/puppy/store/mapstore_test.go
  08_project/nickolee/pkg/puppy/store/storer_test.go
  08_project/nickolee/pkg/puppy/store/syncstore.go
  08_project/nickolee/pkg/puppy/store/syncstore_test.go
  08_project/nickolee/pkg/puppy/types.go
Labels: Merge me, lab8

#498 Lab1: Implement Fibonacci solution and tests
  01_fib/alanhillgemann/main.go
  01_fib/alanhillgemann/main_test.go
Labels: Merge me, lab1

#573 Lab 7 - Errors
  07_errors/kasunfdo/error.go
  07_errors/kasunfdo/error_test.go
  07_errors/kasunfdo/main.go
  07_errors/kasunfdo/main_test.go
  07_errors/kasunfdo/mapstore.go
  07_errors/kasunfdo/store_test.go
  07_errors/kasunfdo/syncstore.go
  07_errors/kasunfdo/types.go
Labels: Merge me, lab7

#509 Lab2: Implement bubble sort solution and tests
  02_bubble/alanhillgemann/main.go
  02_bubble/alanhillgemann/main_test.go
Labels: Merge me, lab2

#584 Lab 10 - Puppy REST
  10_rest/willshen8/README.md
  10_rest/willshen8/cmd/puppy-server/main.go
  10_rest/willshen8/cmd/puppy-server/main_test.go
  10_rest/willshen8/pkg/puppy/error.go
  10_rest/willshen8/pkg/puppy/error_test.go
  10_rest/willshen8/pkg/puppy/mapstore.go
  10_rest/willshen8/pkg/puppy/puppy.go
  10_rest/willshen8/pkg/puppy/rest.go
  10_rest/willshen8/pkg/puppy/rest_test.go
  10_rest/willshen8/pkg/puppy/storer_test.go
  10_rest/willshen8/pkg/puppy/syncstore.go
  go.mod
  go.sum
Labels: Merge me, lab10

#627 Lab9
  09_json/nickolee/README.md
  09_json/nickolee/cmd/puppy-server/main.go
  09_json/nickolee/cmd/puppy-server/main_test.go
  09_json/nickolee/pkg/puppy/error_test.go
  09_json/nickolee/pkg/puppy/errors.go
  09_json/nickolee/pkg/puppy/store/mapstore.go
  09_json/nickolee/pkg/puppy/store/mapstore_test.go
  09_json/nickolee/pkg/puppy/store/storer_test.go
  09_json/nickolee/pkg/puppy/store/syncstore.go
  09_json/nickolee/pkg/puppy/store/syncstore_test.go
  09_json/nickolee/pkg/puppy/types.go
  09_json/nickolee/pkg/puppy/types_test.go
  09_json/nickolee/puppy-data/invalid.json
  09_json/nickolee/puppy-data/puppies.json
  09_json/nickolee/puppy-data/type-mismatch.json
Labels: Changes requested, lab9

#604 Add lab5 - stringer interface
  05_stringer/harirakr/main.go
  05_stringer/harirakr/main_test.go
Labels: Merge me, lab5

#621 Add Lab 8 - Project Layout
  08_project/kasunfdo/README.md
  08_project/kasunfdo/cmd/puppy-server/main.go
  08_project/kasunfdo/cmd/puppy-server/main_test.go
  08_project/kasunfdo/pkg/puppy/error.go
  08_project/kasunfdo/pkg/puppy/error_test.go
  08_project/kasunfdo/pkg/puppy/store/mapstore.go
  08_project/kasunfdo/pkg/puppy/store/store_test.go
  08_project/kasunfdo/pkg/puppy/store/syncstore.go
  08_project/kasunfdo/pkg/puppy/types.go
Labels: Merge me, lab8

#628 Add Lab 9 - JSON puppy
  09_json/kasunfdo/README.md
  09_json/kasunfdo/cmd/puppy-server/main.go
  09_json/kasunfdo/cmd/puppy-server/main_test.go
  09_json/kasunfdo/data/data.json
  09_json/kasunfdo/data/invalidData1.json
  09_json/kasunfdo/data/invalidData2.json
  09_json/kasunfdo/pkg/puppy/error.go
  09_json/kasunfdo/pkg/puppy/error_test.go
  09_json/kasunfdo/pkg/puppy/store/mapstore.go
  09_json/kasunfdo/pkg/puppy/store/store_test.go
  09_json/kasunfdo/pkg/puppy/store/syncstore.go
  09_json/kasunfdo/pkg/puppy/types.go
Labels: Merge me, lab9

#536 Lab7- Errors
  07_errors/mohitnag/error.go
  07_errors/mohitnag/error_test.go
  07_errors/mohitnag/main.go
  07_errors/mohitnag/main_test.go
  07_errors/mohitnag/mapstore.go
  07_errors/mohitnag/store_test.go
  07_errors/mohitnag/syncstore.go
  07_errors/mohitnag/types.go
Labels: Merge me, lab7

#642 Lab10
  10_rest/nickolee/README.md
  10_rest/nickolee/cmd/puppy-server/main.go
  10_rest/nickolee/cmd/puppy-server/main_test.go
  10_rest/nickolee/pkg/puppy/error_test.go
  10_rest/nickolee/pkg/puppy/errors.go
  10_rest/nickolee/pkg/puppy/rest/rest.go
  10_rest/nickolee/pkg/puppy/rest/rest_test.go
  10_rest/nickolee/pkg/puppy/store/mapstore.go
  10_rest/nickolee/pkg/puppy/store/mapstore_test.go
  10_rest/nickolee/pkg/puppy/store/storer_test.go
  10_rest/nickolee/pkg/puppy/store/syncstore.go
  10_rest/nickolee/pkg/puppy/store/syncstore_test.go
  10_rest/nickolee/pkg/puppy/types.go
  10_rest/nickolee/pkg/puppy/types_test.go
  10_rest/nickolee/puppy-data/invalid.json
  10_rest/nickolee/puppy-data/puppies.json
  10_rest/nickolee/puppy-data/type-mismatch.json
Labels: Merge me, lab10

#647 Add Lab 10 - Puppy REST
  10_rest/kasunfdo/README.md
  10_rest/kasunfdo/cmd/puppy-server/main.go
  10_rest/kasunfdo/cmd/puppy-server/main_test.go
  10_rest/kasunfdo/data/data.json
  10_rest/kasunfdo/data/invalidData1.json
  10_rest/kasunfdo/data/invalidData2.json
  10_rest/kasunfdo/pkg/puppy/error.go
  10_rest/kasunfdo/pkg/puppy/error_test.go
  10_rest/kasunfdo/pkg/puppy/puppy.go
  10_rest/kasunfdo/pkg/puppy/rest.go
  10_rest/kasunfdo/pkg/puppy/rest_test.go
  10_rest/kasunfdo/pkg/puppy/store/mapstore.go
  10_rest/kasunfdo/pkg/puppy/store/store_test.go
  10_rest/kasunfdo/pkg/puppy/store/syncstore.go
  go.mod
  go.sum
Labels: Ready for review, lab10

#625 Lab1 - Generate Fibonacci Series
  01_fib/jimbotech/README.md
  01_fib/jimbotech/ex_fibonacci.go
  01_fib/jimbotech/ex_fibonacci_test.go
Labels: Approved by colleague, Merge me, lab1

#617 Lab9-Puppy Store with json tags and cmd line tool
  09_json/mohitnag/README.md
  09_json/mohitnag/cmd/puppy-server/main.go
  09_json/mohitnag/cmd/puppy-server/main_test.go
  09_json/mohitnag/pkg/puppy/error.go
  09_json/mohitnag/pkg/puppy/error_test.go
  09_json/mohitnag/pkg/puppy/store/mapstore.go
  09_json/mohitnag/pkg/puppy/store/store_test.go
  09_json/mohitnag/pkg/puppy/store/storer.go
  09_json/mohitnag/pkg/puppy/store/syncstore.go
  09_json/mohitnag/pkg/puppy/store/testdata/default-puppy.json
  09_json/mohitnag/pkg/puppy/store/testdata/duplicate-puppies.json
  09_json/mohitnag/pkg/puppy/store/testdata/invalid-puppy.json
  09_json/mohitnag/pkg/puppy/store/testdata/many-puppies.json
  09_json/mohitnag/pkg/puppy/types.go
Labels: Merge me, lab9

#605 Implement Lab6 CRUD puppystore
  06_puppy/sirigithub/main.go
  06_puppy/sirigithub/main_test.go
  06_puppy/sirigithub/mapstore.go
  06_puppy/sirigithub/stores_test.go
  06_puppy/sirigithub/syncstore.go
  06_puppy/sirigithub/types.go
Labels: Merge me, lab6

#659 Add Lab 11 - Puppy Notifications
  11_notify/kasunfdo/README.md
  11_notify/kasunfdo/cmd/lostpuppy-service/main.go
  11_notify/kasunfdo/cmd/lostpuppy-service/main_test.go
  11_notify/kasunfdo/cmd/puppy-server/main.go
  11_notify/kasunfdo/cmd/puppy-server/main_test.go
  11_notify/kasunfdo/data/data.json
  11_notify/kasunfdo/data/invalidData1.json
  11_notify/kasunfdo/data/invalidData2.json
  11_notify/kasunfdo/pkg/puppy/error.go
  11_notify/kasunfdo/pkg/puppy/error_test.go
  11_notify/kasunfdo/pkg/puppy/lost.go
  11_notify/kasunfdo/pkg/puppy/lost_test.go
  11_notify/kasunfdo/pkg/puppy/puppy.go
  11_notify/kasunfdo/pkg/puppy/rest.go
  11_notify/kasunfdo/pkg/puppy/rest_test.go
  11_notify/kasunfdo/pkg/puppy/store/mapstore.go
  11_notify/kasunfdo/pkg/puppy/store/store_test.go
  11_notify/kasunfdo/pkg/puppy/store/syncstore.go
  11_notify/kasunfdo/pkg/puppy/util.go
  go.mod
  go.sum
Labels: Merge me, lab11

#673 Update golangci-lint version and disable funlen
  .golangci.yml
  .travis.yml
Labels: Merge me
