Repository anz-bank/go-course, pull requests merged in 2019-11, with the labels that each got.

#653 Add lab 6 - CRUD Puppy with interface
  06_puppy/alextmz/main.go
  06_puppy/alextmz/main_test.go
  06_puppy/alextmz/mapstore.go
  06_puppy/alextmz/storer_test.go
  06_puppy/alextmz/syncstore.go
  06_puppy/alextmz/types.go
Labels: Merge me, lab6

#655 Add lab 7 - Errors
  07_errors/alextmz/errors.go
  07_errors/alextmz/errors_test.go
  07_errors/alextmz/main.go
  07_errors/alextmz/main_test.go
  07_errors/alextmz/mapstore.go
  07_errors/alextmz/storer_test.go
  07_errors/alextmz/syncstore.go
  07_errors/alextmz/types.go
Labels: Merge me, lab7

#644 Add lab 5 - Stringer
  05_stringer/alextmz/main.go
  05_stringer/alextmz/main_test.go
Labels: Merge me, lab5

#640 Add lab 4 - Numeronym
  04_numeronym/alextmz/main.go
  04_numeronym/alextmz/main_test.go
Labels: Ready for review, lab4

#684 Post lab11 fixes
  11_notify/n0npax/cmd/puppy-server/main.go
  11_notify/n0npax/pkg/puppy/errors.go
Labels: Merge me, lab11

#657 Add lab 8 - Project Layout
  08_project/alextmz/README.md
  08_project/alextmz/cmd/puppy-server/main.go
  08_project/alextmz/cmd/puppy-server/main_test.go
  08_project/alextmz/pkg/puppy/errors.go
  08_project/alextmz/pkg/puppy/errors_test.go
  08_project/alextmz/pkg/puppy/store/mapstore.go
  08_project/alextmz/pkg/puppy/store/storer_test.go
  08_project/alextmz/pkg/puppy/store/syncstore.go
  08_project/alextmz/pkg/puppy/types.go
Labels: Changes requested, lab8
