Repository anz-bank/go-course, pull requests merged in 2019-06, with the labels that each got.

#211 lab04 - numeronyms
  04_numeronym/n0npax/main.go
  04_numeronym/n0npax/main_test.go
Labels: Approved by colleague, Merge me, lab4

#131 Lab01 - Implement Fibonacci series
  01_fib/n0npax/main.go
  01_fib/n0npax/main_test.go
Labels: Merge me, lab1

#165 Lab1
  01_fib/CameronSchafer/fib.go
  01_fib/CameronSchafer/fib_test.go
Labels: Approved by colleague, Merge me, lab1

#164 Implement function to print fibonacci series
  01_fib/nicholascross/main.go
  01_fib/nicholascross/main_test.go
Labels: Merge me, lab1

#185 Lab 1 - Fibonacci
  01_fib/willshen8/fib.go
  01_fib/willshen8/fib_test.go
Labels: Approved by colleague, Merge me, lab1

#222 Implement function plus table tests
  01_fib/runnerdave/main.go
  01_fib/runnerdave/main_test.go
Labels: Merge me, lab1

#132 Lab 2 - Bubble sort
  02_bubble/kasunfdo/main.go
  02_bubble/kasunfdo/main_test.go
  02_bubble/kasunfdo/mergesort.go
Labels: Merge me, lab2

#152 LAB1: Implement function that produces Fibonacci sequence
  01_fib/ovlords/main.go
  01_fib/ovlords/main_test.go
Labels: Approved by colleague, Merge me, lab1

#169 01 fib
  01_fib/jonathanheaden/main.go
  01_fib/jonathanheaden/main_test.go
Labels: Merge me, lab1

#133 Lab 3 - Letter frequency
  03_letters/kasunfdo/main.go
  03_letters/kasunfdo/main_test.go
Labels: Merge me, lab3

#145 Lab1 Fibonacci and bonus negafibonacci
  01_fib/pfannerj/main.go
  01_fib/pfannerj/main_test.go
Labels: Merge me, lab1

#215 Complete lab05 - Stringer
  05_stringer/n0npax/main.go
  05_stringer/n0npax/main_test.go
Labels: Approved by colleague, Merge me, lab5

#254 Lab02 - Bubble and insertion sort with unit tests
  02_bubble/willshen8/bubble.go
  02_bubble/willshen8/bubble_test.go
Labels: Merge me, lab2

#209 Lab03 - Letter frequency
  03_letters/n0npax/main.go
  03_letters/n0npax/main_test.go
Labels: Merge me, lab3

#201 Implement sorted letter counting
  03_letters/nicholascross/main.go
  03_letters/nicholascross/main_test.go
Labels: Approved by colleague, Merge me, lab3

#246 Lab1 Fibonacci and Negafibonacci number
  01_fib/jessodri/main.go
  01_fib/jessodri/main_test.go
Labels: Merge me, lab1

#216 Implement numeronyms
  04_numeronym/nicholascross/main.go
  04_numeronym/nicholascross/main_test.go
Labels: Merge me, lab4

#313 lab1 - Implement Fibonacci and Negafibonacci
  01_fib/davidbroughsmyth/main.go
  01_fib/davidbroughsmyth/main_test.go
Labels: Merge me, lab1

#226 Lab1
  .golangci.yml
  .travis.yml
  01_fib/CameronSchafer/fib.go
  01_fib/CameronSchafer/fib_test.go
  01_fib/anzranjana/main.go
  01_fib/anzranjana/main_test.go
  01_fib/kasunfdo/main.go
  01_fib/kasunfdo/main_test.go
  01_fib/n0npax/main.go
  01_fib/n0npax/main_test.go
  01_fib/nicholascross/main.go
  01_fib/nicholascross/main_test.go
  01_fib/willshen8/fib.go
  01_fib/willshen8/fib_test.go
  04_numeronym/n0npax/main.go
  04_numeronym/n0npax/main_test.go
Labels: Changes requested, lab1

#261 Implement bubble and insertion sort
  02_bubble/lexual/sort.go
  02_bubble/lexual/sort_test.go
Labels: Merge me, lab2

#333 Lab03
  03_letters/willshen8/letters.go
  03_letters/willshen8/letters_test.go
Labels: Merge me, lab3

#148 Lab1
  01_fib/lexual/main.go
  01_fib/lexual/main_test.go
Labels: Approved by colleague, Merge me, lab1

#179 Lab 1 - Implement Fibonaci and NegaFibinacci
  01_fib/marksomething/main.go
  01_fib/marksomething/main_test.go
Labels: Approved by colleague, Merge me, lab1

#358 Complete lab06
  06_puppy/n0npax/main.go
  06_puppy/n0npax/main_test.go
  06_puppy/n0npax/memStore.go
  06_puppy/n0npax/store_test.go
  06_puppy/n0npax/syncStore.go
  06_puppy/n0npax/types.go
Labels: Approved by colleague, Merge me, lab6

#174 Implement Lab1
  01_fib/brvishnu92/main.go
  01_fib/brvishnu92/main_test.go
Labels: Merge me, lab1

#238 Implement IPAddr type
  05_stringer/nicholascross/main.go
  05_stringer/nicholascross/main_test.go
Labels: Approved by colleague, Merge me, Ready for review, lab5

#195 Lab1 - Fibonacci function
  01_fib/Jake88/main.go
  01_fib/Jake88/main_test.go
Labels: Merge me, lab1

#406 Add @pentaphobe to CODEOWNERS
  .github/CODEOWNERS
Labels: Ready for review

#243 Implement Bubble sort function plus tests
  02_bubble/runnerdave/main.go
  02_bubble/runnerdave/main_test.go
Labels: Merge me, lab2

#369 Lab05 - Stringers
  05_stringer/willshen8/stringer.go
  05_stringer/willshen8/stringer_test.go
Labels: Approved by colleague, Merge me, lab5

#391 Lab3
  03_letters/brnbke/main.go
  03_letters/brnbke/main_test.go
Labels: Merge me, lab3

#376 Lab4 Numeronym
  04_numeronym/pfannerj/main.go
  04_numeronym/pfannerj/main_test.go
Labels: Approved by colleague, Merge me, lab4

#363 Lab 5 - Stringer
  05_stringer/marksomething/main.go
  05_stringer/marksomething/main_test.go
Labels: Approved by colleague, Merge me, lab5

#239 02_bubble Lab2 commit for review
  02_bubble/saurabhvyas9/main.go
  02_bubble/saurabhvyas9/main_test.go
Labels: Merge me, lab2

#225 01_fib Lab1 commit for review
  01_fib/saurabhvyas9/main.go
  01_fib/saurabhvyas9/main_test.go
Labels: Merge me, lab1

#242 Lab 2 - Sorting
  02_bubble/marksomething/main.go
  02_bubble/marksomething/main_test.go
Labels: Merge me, lab2

#382 Lab5 Stringer
  05_stringer/pfannerj/main.go
  05_stringer/pfannerj/main_test.go
Labels: Approved by colleague, Merge me, lab5

#252 Lab2 Bubble sort and bonus Insertion sort
  02_bubble/pfannerj/main.go
  02_bubble/pfannerj/main_test.go
Labels: Merge me, lab2

#212 Go Lab 1 - calculate Fibonacci and Negafibonacci
  01_fib/brnbke/main.go
  01_fib/brnbke/main_test.go
Labels: Merge me, lab1

#323 Lab 3 - Letter Frequency
  03_letters/jessodri/main.go
  03_letters/jessodri/main_test.go
Labels: Approved by colleague, Merge me, lab3

#466 Implement Lab5 05_Stringer
  05_stringer/saurabhvyas9/main.go
  05_stringer/saurabhvyas9/main_test.go
Labels: Merge me, lab5

#343 Lab01
  01_fib/pokkalar/main.go
  01_fib/pokkalar/main_test.go
Labels: Ready for review, lab1

#219 Implement Bubble and Insertion - Lab 2
  02_bubble/brvishnu92/main.go
  02_bubble/brvishnu92/main_test.go
Labels: Merge me, lab2

#386 Lab1 fibonacci - alfredxiao
  01_fib/alfredxiao/main.go
  01_fib/alfredxiao/main_test.go
Labels: Merge me, lab1

#422 complete lab08
  08_project/n0npax/README.md
  08_project/n0npax/cmd/puppy-server/main.go
  08_project/n0npax/cmd/puppy-server/main_test.go
  08_project/n0npax/pkg/puppy/errors.go
  08_project/n0npax/pkg/puppy/errors_test.go
  08_project/n0npax/pkg/puppy/store/leveldbStore.go
  08_project/n0npax/pkg/puppy/store/leveldbStore_test.go
  08_project/n0npax/pkg/puppy/store/memStore.go
  08_project/n0npax/pkg/puppy/store/store_test.go
  08_project/n0npax/pkg/puppy/store/syncStore.go
  08_project/n0npax/pkg/puppy/types.go
Labels: Merge me, lab8

#274 Implement numeronym & numeronyms functions
  04_numeronym/lexual/numeronym.go
  04_numeronym/lexual/numeronym_test.go
Labels: Merge me, lab4

#390 Lab 4 - Implemented Numeronyms
  04_numeronym/joel00wood/main.go
  04_numeronym/joel00wood/main_test.go
Labels: Merge me, lab4

#206 Lab02
  02_bubble/jonathanheaden/main.go
  02_bubble/jonathanheaden/main_test.go
Labels: Approved by colleague, Merge me, lab2

#182 Lab 2 - Sorting
  02_bubble/n0npax/main.go
  02_bubble/n0npax/main_test.go
Labels: Approved by colleague, Merge me, Ready for review, lab2

#281 Lab1
  01_fib/cuminandpaprika/main.go
  01_fib/cuminandpaprika/main_test.go
Labels: Merge me, lab1

#134 Lab 4 - Numeronym
  04_numeronym/kasunfdo/main.go
  04_numeronym/kasunfdo/main_test.go
Labels: Merge me, lab4

#467 Implemented Fibonacci sequence and tests Lab1
  01_fib/sirigithub/main.go
  01_fib/sirigithub/main_test.go
Labels: Merge me, lab1

#339 Adds Fibbonacci and Tests
  01_fib/mohitnag/main.go
  01_fib/mohitnag/main_test.go
Labels: Merge me, lab1

#347 Lab 3 - Letter Frequency
  03_letters/marksomething/main.go
  03_letters/marksomething/main_test.go
Labels: Merge me, lab3

#337 Lab04 - Numeronyms
  04_numeronym/willshen8/numeronyms.go
  04_numeronym/willshen8/numeronyms_test.go
Labels: Merge me, lab4

#497 Allow duplicated code in golangci conf
  .golangci.yml
Labels: Ready for review

#227 lab1 - Created Fibonacci sequencer
  01_fib/joel00wood/main.go
  01_fib/joel00wood/main_test.go
Labels: Merge me, lab1

#433 Implement 03_letters
  03_letters/saurabhvyas9/main.go
  03_letters/saurabhvyas9/main_test.go
Labels: Approved by colleague, Merge me, lab3

#355 Lab 4 - Numeronyms
  04_numeronym/marksomething/main.go
  04_numeronym/marksomething/main_test.go
Labels: Approved by colleague, Merge me, lab4

#265 Implement Lab4 - Numeronym
  04_numeronym/brvishnu92/main.go
  04_numeronym/brvishnu92/main_test.go
Labels: Approved by colleague, Merge me, lab4

#502 Implement fibonacci sequence for positive integers
  01_fib/undrewb/main.go
  01_fib/undrewb/main_test.go
Labels: Approved by colleague, lab1

#438 Lab4 Implement numeronyms and tests
  04_numeronym/alfredxiao/main.go
  04_numeronym/alfredxiao/main_test.go
Labels: Merge me, lab4

#389 Lab3 - implemented letter count also sorting, tests included - alfredxiao
  03_letters/alfredxiao/main.go
  03_letters/alfredxiao/main_test.go
Labels: Merge me, lab3

#445 Lab5 - Implement String() and add tests
  05_stringer/alfredxiao/main.go
  05_stringer/alfredxiao/main_test.go
Labels: Merge me, lab5

#435 Implement Lab 4 - 04_Numeronym
  04_numeronym/saurabhvyas9/main.go
  04_numeronym/saurabhvyas9/main_test.go
Labels: Merge me, lab4
