Repository anz-bank/go-course, pull requests merged in 2019-02, with the labels that each got.

#39 Printing Fibonacci series
  01_fib/main.go
  01_fib/main_test.go
Labels: Approved by colleague

#45 Implement a method that sorts an integer slice using BubbleSort
  02_bubble/mohankrishna/main.go
  02_bubble/mohankrishna/main_test.go
Labels: Reviewed by Codeowner, lab2

#19 Lab 1 - Fibonacci
  01_fib/mohankrishna/main.go
  01_fib/mohankrishna/main_test.go
Labels: Ready for review, lab1

#41 Implement Bubble, Insertion sort and a unit test coverage
  02_bubble/madhavansu/main.go
  02_bubble/madhavansu/main_test.go
Labels: Approved by colleague, lab2

#44 Bubble Sort Implementation
  02_bubble/srini/main.go
  02_bubble/srini/main_test.go
Labels: Approved by colleague, lab2

#66 Lab 3 - Letter frequency
  03_letters/mohankrishna/main.go
  03_letters/mohankrishna/main_test.go
Labels: Approved by colleague, lab3

#61 Lab2 bubble sort
  02_bubble/sahidakhtar1/main.go
  02_bubble/sahidakhtar1/main_test.go
Labels: Approved by colleague, lab2

#64 Lab3
  03_letters/srini/main.go
  03_letters/srini/main_test.go
Labels: Approved by colleague, lab3

#60 Calculate and print first n Fibonacci numbers and related tests
  01_fib/srini/main.go
  01_fib/srini/main_test.go
Labels: Approved by colleague, lab1

#56 Lab2 Bubble sort
  02_bubble/vinilapeddireddy/bubblesort.go
  02_bubble/vinilapeddireddy/bubblesort_test.go
Labels: Approved by colleague, lab2

#84 Lab 4 and 5: Numeronym and Stringers implementation
  04_numeronym/madhavansu/main.go
  04_numeronym/madhavansu/main_test.go
  05_stringer/madhavansu/main.go
  05_stringer/madhavansu/main_test.go
Labels: Approved by colleague, lab4, lab5

#92 Lab 3 - Letter frequency implementation
  03_letters/madhavansu/main.go
  03_letters/madhavansu/main_test.go
Labels: Approved by colleague, lab3

#94 05 stringer
  05_stringer/sahidakhtar1/main.go
  05_stringer/sahidakhtar1/main_test.go
Labels: Approved by colleague, lab5

#69 Lab3 letter frequency
  03_letters/vinilapeddireddy/main.go
  03_letters/vinilapeddireddy/main_test.go
Labels: Approved by colleague, lab3

#72 Program to return numeronyms for a given set of strings
  04_numeronym/srini/main.go
  04_numeronym/srini/main_test.go
Labels: Approved by colleague, lab4

#83 Lab4 and 5: Numeronyms and Stringer
  04_numeronym/amitkrishna/numeronym.go
  04_numeronym/amitkrishna/numeronym_test.go
  05_stringer/amitkrishna/stringer.go
  05_stringer/amitkrishna/stringer_test.go
Labels: Approved by colleague, lab4, lab5

#73 Lab 4 and 5 - numeronyms and stringer interface
  04_numeronym/mohankrishna/main.go
  04_numeronym/mohankrishna/main_test.go
  05_stringer/mohankrishna/main.go
  05_stringer/mohankrishna/main_test.go
Labels: Approved by colleague, lab4, lab5

#46 Sort an array using bubble sort logic
  02_bubble/paraganz/main.go
  02_bubble/paraganz/main_test.go
Labels: Approved by colleague, lab2

#75 Numeronyms and stringer interface
  04_numeronym/paraganz/main.go
  04_numeronym/paraganz/main_test.go
  05_stringer/paraganz/main.go
  05_stringer/paraganz/main_test.go
Labels: Approved by colleague, lab4, lab5

#97 Program to implement IP Address Type and also Stringer interface
  05_stringer/main.go
  05_stringer/main_test.go
Labels: Approved by colleague, lab5

#81 Lab 04 numeronym
  04_numeronym/sahidakhtar1/main.go
  04_numeronym/sahidakhtar1/main_test.go
Labels: Approved by colleague, lab4

#99 Lab 6 - CRUD puppy with interface
  06_puppy/mohankrishna/main.go
  06_puppy/mohankrishna/map_store.go
  06_puppy/mohankrishna/storer_test.go
  06_puppy/mohankrishna/sync_store.go
  06_puppy/mohankrishna/types.go
Labels: Approved by colleague, lab6

#107 Lab 01 - Implement fibonacci series
  01_fib/jecofang/fib.go
  01_fib/jecofang/fib_test.go
Labels: Approved by colleague, lab1

#105 Lab 6 - Create CRUD puppy with interface
  06_puppy/madhavansu/main.go
  06_puppy/madhavansu/main_test.go
  06_puppy/madhavansu/mapstore.go
  06_puppy/madhavansu/storer.go
  06_puppy/madhavansu/syncstore.go
  06_puppy/madhavansu/types.go
Labels: Approved by colleague, lab6
