Repository anz-bank/go-course, pull requests merged in 2019-08, with the labels that each got.

#360 Lab4
  04_numeronym/hsy3418/main.go
  04_numeronym/hsy3418/main_test.go
Labels: Merge me, lab4

#374 Bubble sort and its tests
  02_bubble/mohitnag/main.go
  02_bubble/mohitnag/main_test.go
Labels: Merge me, lab2

#315 Lab3
  03_letters/hsy3418/main.go
  03_letters/hsy3418/main_test.go
Labels: Merge me, lab3

#383 Complete lab07
  07_errors/n0npax/errors.go
  07_errors/n0npax/errors_test.go
  07_errors/n0npax/main.go
  07_errors/n0npax/main_test.go
  07_errors/n0npax/memStore.go
  07_errors/n0npax/store_test.go
  07_errors/n0npax/syncStore.go
  07_errors/n0npax/types.go
Labels: Merge me, lab7

#501 Lab 5: Stringer
  05_stringer/nickolee/stringer.go
  05_stringer/nickolee/stringer_test.go
Labels: Merge me, lab5

#555 Lab08 - Project Layout
  08_project/willshen8/README.md
  08_project/willshen8/cmd/puppy-server/main.go
  08_project/willshen8/cmd/puppy-server/main_test.go
  08_project/willshen8/pkg/puppy/error.go
  08_project/willshen8/pkg/puppy/store/mapstore.go
  08_project/willshen8/pkg/puppy/store/storer.go
  08_project/willshen8/pkg/puppy/store/storer_test.go
  08_project/willshen8/pkg/puppy/store/syncstore.go
  08_project/willshen8/pkg/puppy/types.go
Labels: Merge me, lab8

#562 Lab09 - JSON puppy
  09_json/willshen8/README.md
  09_json/willshen8/cmd/puppy-server/main.go
  09_json/willshen8/cmd/puppy-server/main_test.go
  09_json/willshen8/pkg/puppy/error.go
  09_json/willshen8/pkg/puppy/store/mapstore.go
  09_json/willshen8/pkg/puppy/store/storer.go
  09_json/willshen8/pkg/puppy/store/storer_test.go
  09_json/willshen8/pkg/puppy/store/syncstore.go
  09_json/willshen8/pkg/puppy/store/types_test.go
  09_json/willshen8/pkg/puppy/types.go
  09_json/willshen8/puppyData/invalid_puppies.json
  09_json/willshen8/puppyData/puppies.json
  09_json/willshen8/puppyData/puppy.json
  09_json/willshen8/puppyData/type_mismatch.json
  go.mod
  go.sum
Labels: Ready for review, lab9

#571 Marshalling json
  09_json/runnerdave/README.md
  09_json/runnerdave/cmd/puppy_server/main.go
  09_json/runnerdave/cmd/puppy_server/main_test.go
  09_json/runnerdave/pkg/puppy/errors.go
  09_json/runnerdave/pkg/puppy/errors_test.go
  09_json/runnerdave/pkg/puppy/store/map_store.go
  09_json/runnerdave/pkg/puppy/store/storer_stringer_test.go
  09_json/runnerdave/pkg/puppy/store/storer_test.go
  09_json/runnerdave/pkg/puppy/store/sync_store.go
  09_json/runnerdave/pkg/puppy/types.go
  09_json/runnerdave/pkg/puppy/types_test.go
  09_json/runnerdave/puppydata/data.json
  09_json/runnerdave/puppydata/invalid-data.json
  09_json/runnerdave/puppydata/invalid-puppies.json
  09_json/runnerdave/puppydata/repeated-puppy.json
Labels: Under review, lab9

#494 Implement numeronyms function and write test cases
  04_numeronym/nickolee/numeronym.go
  04_numeronym/nickolee/numeronym_test.go
Labels: Merge me, lab4

#522 Lab6- Add PuppyStore and tests
  06_puppy/mohitnag/main.go
  06_puppy/mohitnag/main_test.go
  06_puppy/mohitnag/mapstore.go
  06_puppy/mohitnag/store_test.go
  06_puppy/mohitnag/syncstore.go
  06_puppy/mohitnag/types.go
Labels: Merge me, lab6

#561 Project layout
  08_project/runnerdave/README.md
  08_project/runnerdave/cmd/puppy-server/main.go
  08_project/runnerdave/cmd/puppy-server/main_test.go
  08_project/runnerdave/pkg/puppy/errors.go
  08_project/runnerdave/pkg/puppy/store/map_store.go
  08_project/runnerdave/pkg/puppy/store/storer_test.go
  08_project/runnerdave/pkg/puppy/store/sync_store.go
  08_project/runnerdave/pkg/puppy/types.go
Labels: Merge me, lab8

#489 Complete lab9
  09_json/n0npax/README.md
  09_json/n0npax/cmd/puppy-server/main.go
  09_json/n0npax/cmd/puppy-server/main_test.go
  09_json/n0npax/pkg/puppy/errors.go
  09_json/n0npax/pkg/puppy/errors_test.go
  09_json/n0npax/pkg/puppy/store/memStore.go
  09_json/n0npax/pkg/puppy/store/store_test.go
  09_json/n0npax/pkg/puppy/store/syncStore.go
  09_json/n0npax/pkg/puppy/types.go
  09_json/n0npax/pkg/puppy/types_test.go
Labels: Merge me, lab9

#504 Complete lab 10
  10_rest/n0npax/README.md
  10_rest/n0npax/cmd/puppy-server/main.go
  10_rest/n0npax/cmd/puppy-server/main_test.go
  10_rest/n0npax/pkg/puppy/errors.go
  10_rest/n0npax/pkg/puppy/errors_test.go
  10_rest/n0npax/pkg/puppy/rest.go
  10_rest/n0npax/pkg/puppy/rest_test.go
  10_rest/n0npax/pkg/puppy/store/memStore.go
  10_rest/n0npax/pkg/puppy/store/store_test.go
  10_rest/n0npax/pkg/puppy/store/syncStore.go
  10_rest/n0npax/pkg/puppy/types.go
  10_rest/n0npax/pkg/puppy/types_test.go
Labels: Merge me, lab10

#527 Lab5
  05_stringer/hsy3418/main.go
  05_stringer/hsy3418/main_test.go
Labels: Merge me, lab5

#551 Lab6 CRUD Puppy
  06_puppy/pfannerj/main.go
  06_puppy/pfannerj/main_test.go
  06_puppy/pfannerj/mapstore.go
  06_puppy/pfannerj/storer_test.go
  06_puppy/pfannerj/syncstore.go
  06_puppy/pfannerj/types.go
Labels: Merge me, lab6

#464 Lab4
  04_numeronym/CameronSchafer/main.go
  04_numeronym/CameronSchafer/main_test.go
Labels: Merge me, lab4

#554 Lab2: implement bubble sort
  02_bubble/ailyntang/sort.go
  02_bubble/ailyntang/sort_test.go
Labels: Merge me, lab2

#594 Add lab1 - Fibonacci series
  01_fib/harirakr/main.go
  01_fib/harirakr/main_test.go
Labels: Merge me, lab1

#578 Lab11
  11_notify/n0npax/README.md
  11_notify/n0npax/cmd/lostpuppy-service/main.go
  11_notify/n0npax/cmd/lostpuppy-service/main_test.go
  11_notify/n0npax/cmd/puppy-server/main.go
  11_notify/n0npax/cmd/puppy-server/main_test.go
  11_notify/n0npax/pkg/middleware/slowerer.go
  11_notify/n0npax/pkg/middleware/slowerer_test.go
  11_notify/n0npax/pkg/puppy/errors.go
  11_notify/n0npax/pkg/puppy/errors_test.go
  11_notify/n0npax/pkg/puppy/lostService.go
  11_notify/n0npax/pkg/puppy/lostService_test.go
  11_notify/n0npax/pkg/puppy/rest.go
  11_notify/n0npax/pkg/puppy/rest_test.go
  11_notify/n0npax/pkg/puppy/store/memStore.go
  11_notify/n0npax/pkg/puppy/store/store_test.go
  11_notify/n0npax/pkg/puppy/store/syncStore.go
  11_notify/n0npax/pkg/puppy/types.go
  11_notify/n0npax/pkg/puppy/types_test.go
  go.mod
  go.sum
Labels: Merge me, lab11

#583 Lab3-letter
  03_letters/nicholeL/main.go
  03_letters/nicholeL/main_test.go
Labels: Merge me, lab3

#342 Lab 6 - CRUD puppy with interface
  06_puppy/kasunfdo/main.go
  06_puppy/kasunfdo/main_test.go
  06_puppy/kasunfdo/mapstore.go
  06_puppy/kasunfdo/store_test.go
  06_puppy/kasunfdo/syncstore.go
  06_puppy/kasunfdo/types.go
Labels: Merge me, lab6

#598 Lab02 - Bubble sort and Insertion sort #597
  02_bubble/pokkalar/main.go
  02_bubble/pokkalar/main_test.go
Labels: Merge me, lab2

#600 Add lab3 - letter count
  03_letters/harirakr/main.go
  03_letters/harirakr/main_test.go
Labels: Merge me, lab3

#602 Add lab4 - numeronyms
  04_numeronym/harirakr/main.go
  04_numeronym/harirakr/main_test.go
Labels: Merge me, lab4

#596 Add lab2 - Bubble and Insertion sort
  02_bubble/harirakr/main.go
  02_bubble/harirakr/main_test.go
Labels: lab2

#567 Lab6
  06_puppy/nickolee/mapstore.go
  06_puppy/nickolee/mapstore_test.go
  06_puppy/nickolee/storer_test.go
  06_puppy/nickolee/syncstore.go
  06_puppy/nickolee/syncstore_test.go
  06_puppy/nickolee/types.go
Labels: Merge me, lab6

#529 Lab5: Implement stringer solution and tests
  05_stringer/alanhillgemann/main.go
  05_stringer/alanhillgemann/main_test.go
Labels: Merge me, lab5

#582 Lab8- Project Layout
  08_project/mohitnag/README.md
  08_project/mohitnag/cmd/puppy-server/main.go
  08_project/mohitnag/cmd/puppy-server/main_test.go
  08_project/mohitnag/pkg/puppy/error.go
  08_project/mohitnag/pkg/puppy/error_test.go
  08_project/mohitnag/pkg/puppy/store/mapstore.go
  08_project/mohitnag/pkg/puppy/store/store_test.go
  08_project/mohitnag/pkg/puppy/store/syncstore.go
  08_project/mohitnag/pkg/puppy/types.go
Labels: Merge me, lab8

#615 Implement lab7 custom errors
  07_errors/nickolee/error.go
  07_errors/nickolee/error_test.go
  07_errors/nickolee/mapstore.go
  07_errors/nickolee/mapstore_test.go
  07_errors/nickolee/storer_test.go
  07_errors/nickolee/syncstore.go
  07_errors/nickolee/syncstore_test.go
  07_errors/nickolee/types.go
Labels: Merge me, lab7
