Repository anz-bank/go-course, pull requests merged in 2019-07, with the labels that each got.

#375 Implement tests and function to produce numeronyms
  04_numeronym/runnerdave/main.go
  04_numeronym/runnerdave/main_test.go
Labels: Approved by colleague, Merge me, lab4

#352 Letter frequency
  03_letters/runnerdave/main.go
  03_letters/runnerdave/main_test.go
Labels: Merge me, lab3

#277 Implement Stringer - Lab 5
  05_stringer/brvishnu92/main.go
  05_stringer/brvishnu92/main_test.go
Labels: Approved by colleague, Merge me, lab5

#263 Implement Lab3 - Letter Frequency
  03_letters/brvishnu92/main.go
  03_letters/brvishnu92/main_test.go
Labels: Approved by colleague, Merge me, lab3

#318 Lab 5 - Stringer
  05_stringer/kasunfdo/main.go
  05_stringer/kasunfdo/main_test.go
Labels: Approved by colleague, Merge me, lab5

#385 Implement type for IP address with stringer interface plus tests
  05_stringer/runnerdave/main.go
  05_stringer/runnerdave/main_test.go
Labels: Approved by colleague, Merge me, lab5

#423 Add Fibonacci sequence generator
  01_fib/patrickmarabeas/main.go
  01_fib/patrickmarabeas/main_test.go
Labels: Merge me, lab1

#426 Add numeronyms functionality
  04_numeronym/patrickmarabeas/main.go
  04_numeronym/patrickmarabeas/main_test.go
Labels: Approved by colleague, Merge me, lab4

#180 Bubble and insertion sort
  02_bubble/nicholascross/main.go
  02_bubble/nicholascross/maint_test.go
Labels: Merge me, lab2

#425 Add letter frequency functionality
  03_letters/patrickmarabeas/main.go
  03_letters/patrickmarabeas/main_test.go
Labels: Approved by colleague, Merge me, lab3

#283 Make the IPAddr type implement fmt.Stringer
  05_stringer/lexual/stringer.go
  05_stringer/lexual/stringer_test.go
Labels: Approved by colleague, Merge me, lab5

#332 Lab2 - Implemented Sorting Algorithm
  02_bubble/joel00wood/main.go
  02_bubble/joel00wood/main_test.go
Labels: Approved by colleague, Merge me, lab2

#359 Lab 3 - Built Letter Frequency Analyser
  03_letters/joel00wood/main.go
  03_letters/joel00wood/main_test.go
Labels: Approved by colleague, Merge me, lab3

#394 Lab 5 - Created IPAddr data type
  05_stringer/joel00wood/main.go
  05_stringer/joel00wood/main_test.go
Labels: Approved by colleague, Merge me, lab5

#474 Lab06 - Puppy Storer
  06_puppy/willshen8/mapStore.go
  06_puppy/willshen8/puppy.go
  06_puppy/willshen8/puppy_test.go
  06_puppy/willshen8/storer.go
  06_puppy/willshen8/storer_test.go
  06_puppy/willshen8/syncStore.go
Labels: Approved by colleague, Merge me, Ready for review, lab6

#431 Lab5 Creating Stringer for IPAddr
  05_stringer/brnbke/main.go
  05_stringer/brnbke/main_test.go
Labels: Approved by colleague, Merge me, lab5

#436 Puppy store
  06_puppy/runnerdave/main.go
  06_puppy/runnerdave/main_test.go
  06_puppy/runnerdave/map_store.go
  06_puppy/runnerdave/storer_test.go
  06_puppy/runnerdave/sync_store.go
  06_puppy/runnerdave/types.go
Labels: Merge me, lab6

#487 Lab2 Added Bubble and Insertion sort functions
  02_bubble/davidbroughsmyth/main.go
  02_bubble/davidbroughsmyth/main_test.go
Labels: Approved by colleague, Merge me, lab2

#520 Lab3: Implement letter frequency solution and tests
  03_letters/alanhillgemann/main.go
  03_letters/alanhillgemann/main_test.go
Labels: lab3

#542 Implemented Lab4 numeronym and test cases
  04_numeronym/sirigithub/main.go
  04_numeronym/sirigithub/main_test.go
Labels: Approved by colleague, Merge me, Ready for review, lab4

#408 Lab 3 - Letter frequency
  03_letters/mohitnag/main.go
  03_letters/mohitnag/main_test.go
Labels: Approved by colleague, Merge me, lab3

#351 Lab3 Letter Frequency
  03_letters/pfannerj/main.go
  03_letters/pfannerj/main_test.go
Labels: Merge me, Ready for review, lab3

#524 Lab4: Implement numeronym solution and tests
  04_numeronym/alanhillgemann/main.go
  04_numeronym/alanhillgemann/main_test.go
Labels: lab4

#329 Lab 5 - Stringer
  05_stringer/jessodri/main.go
  05_stringer/jessodri/main_test.go
Labels: Approved by colleague, Merge me, lab5

#325 Lab 2 - Adding multiple sort functions
  02_bubble/brnbke/main.go
  02_bubble/brnbke/main_test.go
Labels: Approved by colleague, Merge me, lab2

#403 Lab4 Numeronym function
  04_numeronym/brnbke/main.go
  04_numeronym/brnbke/main_test.go
Labels: Approved by colleague, Merge me, lab4

#557 Puppy store error handling
  07_errors/runnerdave/errors.go
  07_errors/runnerdave/main.go
  07_errors/runnerdave/main_test.go
  07_errors/runnerdave/map_store.go
  07_errors/runnerdave/storer_test.go
  07_errors/runnerdave/sync_store.go
  07_errors/runnerdave/types.go
Labels: Merge me, Ready for review, lab7

#308 Lab 2 - Bubble sort
  02_bubble/jessodri/main.go
  02_bubble/jessodri/main_test.go
Labels: Approved by colleague, Merge me, lab2

#541 Lab1: implement Fibonacci function
  01_fib/ailyntang/fib.go
  01_fib/ailyntang/fib_test.go
Labels: Approved by colleague, Under review, lab1

#478 Lab3
  03_letters/nickolee/letter_frequency.go
  03_letters/nickolee/letter_frequency_test.go
Labels: Merge me, lab3

#471 Lab2 Complete bubble sort algorithm and write test scripts
  02_bubble/nickolee/bubblesort.go
  02_bubble/nickolee/bubblesort_test.go
Labels: Merge me, lab2

#531 Lab07 - Errors
  07_errors/willshen8/error.go
  07_errors/willshen8/mapStore.go
  07_errors/willshen8/puppy.go
  07_errors/willshen8/puppy_test.go
  07_errors/willshen8/storer.go
  07_errors/willshen8/storer_test.go
  07_errors/willshen8/syncStore.go
Labels: Merge me, lab7

#387 Lab2 Implemented bubble and insertion sort
  02_bubble/sirigithub/main.go
  02_bubble/sirigithub/main_test.go
Labels: Merge me, lab2

#515 Implement Lab3 Letter frequency
  03_letters/sirigithub/main.go
  03_letters/sirigithub/main_test.go
Labels: Merge me, lab3

#155 create a fibonacci number generator function
  01_fib/hsy3418/main.go
  01_fib/hsy3418/main_test.go
Labels: Merge me, lab1

#294 Lab2
  02_bubble/hsy3418/main.go
  02_bubble/hsy3418/main_test.go
Labels: Merge me, lab2

#552 Implement Lab5 Stringer and tests
  05_stringer/sirigithub/main.go
  05_stringer/sirigithub/main_test.go
Labels: Merge me, lab5

#545 Lab3 - Add Letter frequency and sort letters functions
  03_letters/davidbroughsmyth/main.go
  03_letters/davidbroughsmyth/main_test.go
Labels: Merge me, lab3

#549 Lab5 - Add IPAddr type and implement fmt.Stringer
  05_stringer/davidbroughsmyth/main.go
  05_stringer/davidbroughsmyth/main_test.go
Labels: Merge me, lab5

#547 Lab4 - Add numeronyms function
  04_numeronym/davidbroughsmyth/main.go
  04_numeronym/davidbroughsmyth/main_test.go
Labels: Merge me, lab4

#412 Lab5 - Stringer
  05_stringer/mohitnag/main.go
  05_stringer/mohitnag/main_test.go
Labels: Merge me, lab5

#192 Lab2 Bubble & Insertion sort
  02_bubble/CameronSchafer/bubble.go
  02_bubble/CameronSchafer/bubble_test.go
Labels: Merge me, lab2

#327 Lab 4 - Numeronyms
  04_numeronym/jessodri/main.go
  04_numeronym/jessodri/main_test.go
Labels: Merge me, lab4

#235 Lab3
  03_letters/CameronSchafer/main.go
  03_letters/CameronSchafer/main_test.go
Labels: Merge me, lab3

#424 Add bubble and insertion sort algorithms
  02_bubble/patrickmarabeas/main.go
  02_bubble/patrickmarabeas/main_test.go
Labels: Merge me, lab2

#427 Add IPAddr type
  05_stringer/patrickmarabeas/main.go
  05_stringer/patrickmarabeas/main_test.go
Labels: Merge me, lab5

#251 Lab5 - Stringer
  05_stringer/CameronSchafer/main.go
  05_stringer/CameronSchafer/main_test.go
Labels: Merge me, lab5

#410 Lab4- Numeronym
  04_numeronym/mohitnag/main.go
  04_numeronym/mohitnag/main_test.go
Labels: Merge me, lab4

#506 Lab2 - Implement bubble and insertion sort, and tests
  02_bubble/alfredxiao/main.go
  02_bubble/alfredxiao/main_test.go
Labels: Merge me, lab2
