Repository anz-bank/go-course, pull requests merged in 2019-10, with the labels that each got.

#649 Lab10- Puppy Store Rest layer
  10_rest/mohitnag/README.md
  10_rest/mohitnag/cmd/puppy-server/main.go
  10_rest/mohitnag/cmd/puppy-server/main_test.go
  10_rest/mohitnag/pkg/puppy/error.go
  10_rest/mohitnag/pkg/puppy/error_test.go
  10_rest/mohitnag/pkg/puppy/store/mapstore.go
  10_rest/mohitnag/pkg/puppy/store/store_test.go
  10_rest/mohitnag/pkg/puppy/store/storer.go
  10_rest/mohitnag/pkg/puppy/store/syncstore.go
  10_rest/mohitnag/pkg/puppy/store/testdata/default-puppy.json
  10_rest/mohitnag/pkg/puppy/store/testdata/duplicate-puppies.json
  10_rest/mohitnag/pkg/puppy/store/testdata/invalid-puppy.json
  10_rest/mohitnag/pkg/puppy/store/testdata/many-puppies.json
  10_rest/mohitnag/pkg/puppy/types.go
  10_rest/mohitnag/pkg/rest/rest.go
  10_rest/mohitnag/pkg/rest/rest_test.go
Labels: Merge me, lab10

#636 Lab 10
  10_rest/runnerdave/README.md
  10_rest/runnerdave/cmd/puppy_server/main.go
  10_rest/runnerdave/cmd/puppy_server/main_test.go
  10_rest/runnerdave/pkg/puppy/errors.go
  10_rest/runnerdave/pkg/puppy/errors_test.go
  10_rest/runnerdave/pkg/puppy/rest.go
  10_rest/runnerdave/pkg/puppy/rest_test.go
  10_rest/runnerdave/pkg/puppy/store/map_store.go
  10_rest/runnerdave/pkg/puppy/store/storer_stringer_test.go
  10_rest/runnerdave/pkg/puppy/store/storer_test.go
  10_rest/runnerdave/pkg/puppy/store/sync_store.go
  10_rest/runnerdave/pkg/puppy/types.go
  10_rest/runnerdave/pkg/puppy/types_test.go
  10_rest/runnerdave/puppydata/data.json
  10_rest/runnerdave/puppydata/invalid-data.json
  10_rest/runnerdave/puppydata/invalid-puppies-negative-value.json
  10_rest/runnerdave/puppydata/invalid-puppies.json
  10_rest/runnerdave/puppydata/repeated-puppy.json
Labels: Merge me, lab10

#622 Add lab 1, Fibonacci numbers
  01_fib/alextmz/main.go
  01_fib/alextmz/main_test.go
Labels: Merge me, lab1

#661 Lab11 - Puppy Notifiaction
  11_notify/willshen8/README.md
  11_notify/willshen8/cmd/lostpuppy-service/main.go
  11_notify/willshen8/cmd/lostpuppy-service/main_test.go
  11_notify/willshen8/cmd/puppy-server/main.go
  11_notify/willshen8/cmd/puppy-server/main_test.go
  11_notify/willshen8/pkg/puppy/error.go
  11_notify/willshen8/pkg/puppy/error_test.go
  11_notify/willshen8/pkg/puppy/lostpuppy.go
  11_notify/willshen8/pkg/puppy/lostpuppy_test.go
  11_notify/willshen8/pkg/puppy/mapstore.go
  11_notify/willshen8/pkg/puppy/puppy.go
  11_notify/willshen8/pkg/puppy/rest.go
  11_notify/willshen8/pkg/puppy/rest_test.go
  11_notify/willshen8/pkg/puppy/storer_test.go
  11_notify/willshen8/pkg/puppy/syncstore.go
  go.mod
  go.sum
Labels: Merge me, lab11

#645 Lab 4 - Numeronym
  04_numeronym/jimbotech/README.md
  04_numeronym/jimbotech/numeronym.go
  04_numeronym/jimbotech/numeronym_test.go
Labels: Merge me, lab4

#634 Implement lab 3 - letters
  03_letters/jimbotech/README.md
  03_letters/jimbotech/lab3_letter.go
  03_letters/jimbotech/lab3_letter_test.go
Labels: Merge me, lab3

#631 Initial commit for lab2 the bubble sort
  02_bubble/jimbotech/README.md
  02_bubble/jimbotech/bubble.go
  02_bubble/jimbotech/bubble_test.go
Labels: Merge me, lab2

#663 Stringer implementation for Lab 5
  05_stringer/jimbotech/stringer.go
  05_stringer/jimbotech/stringer_test.go
Labels: Merge me, lab5

#624 Add lab 2, bubblesort
  02_bubble/alextmz/main.go
  02_bubble/alextmz/main_test.go
Labels: Merge me, lab2
